In [ ]:
import os
os.chdir("/content/drive/My Drive/PH240C_Project")

In [ ]:
pip install igraph

In [ ]:
from random import sample
from nonlinear_learning import *
import pandas as pd

In [ ]:
import rpy2.robjects as robjects
robjects.r['load']("s5_ECoG_label.RData")
series_low = np.array(robjects.r['ofc_s05'][0][0])
series_high = np.array(robjects.r['ofc_s05'][0][1])
xs_low = np.mean(series_low[0:10,:,:],0)
xs_high = np.mean(series_high[0:10,:,:],0)
xs_low  = (xs_low - np.mean(xs_low,0))/np.std(xs_low,0)
xs_high  = (xs_high - np.mean(xs_high,0))/np.std(xs_high,0)

In [ ]:
torch.manual_seed(2) 
max_iter=20
lambda0=0.05
w_threshold=0.1
d = xs_low.shape[1]
model=NotearsMLP(dims=[d, 10, 1], bias=True)
W_low_t = notears_nonlinear(model, xs_low, lambda1=lambda0, lambda2=lambda0, w_threshold=w_threshold,max_iter=max_iter)
W_low = W_low_t.T

0
1
2


In [ ]:
node_label = []
node_edge_num_in = []
node_edge_num_out = []
for i in range(d):
    node_label.append(i+1)
    node_edge_num_in.append(np.sum(W_low[i,:]!=0))
    node_edge_num_out.append(np.sum(W_low[:,i]!=0))

data = {'node_label': node_label , 'node_edge_num_in': node_edge_num_in , 'node_edge_num_out': node_edge_num_out}
df = pd.DataFrame(data=data)
pd.set_option('display.max_rows', df.shape[0]+1)
df

node_label  node_edge_num_in  node_edge_num_out
0            1                 0                  0
1            2                 0                  0
2            3                 0                  0
3            4                 0                  0
4            5                 0                  0
5            6                 0                  0
6            7                 0                  0
7            8                 0                  0
8            9                 0                  0
9           10                 0                  0
10          11                 0                  0
11          12                 0                  0
12          13                 0                  0
13          14                 0                  0
14          15                 0                  0
15          16                 0                  1
16          17                 0                  0
17          18                 4                  0
18          19                 0                  1
19          20                 0                  0
20          21                 0                  0
21          22                 0                  2
22          23                 4                  0
23          24                 0                  0
24          25                 0                  0
25          26                 0                  0
26          27                 0                  0
27          28                 0                  0
28          29                 0                  0
29          30                 0                  0
30          31                 0                  1
31          32                 0                  0
32          33                 0                  0
33          34                 0                  1
34          35                 0                  0
35          36                 0                  0
36          37                 0                  0
37          38                 0                  0
38          39                 0                  0
39          40                 0                  0
40          41                 0                  1
41          42                 0                  0
42          43                 0                  0
43          44                 0                  0
44          45                 0                  1
45          46                 0                  0
46          47                 0                  0
47          48                 0                  0
48          49                 0                  0
49          50                 0                  0
50          51                 0                  0
51          52                 0                  0
52          53                 0                  0
53          54                 0                  0
54          55                 0                  0
55          56                 0                  0
56          57                 0                  0
57          58                 0                  0
58          59                 1                  0
59          60                 0                  0
60          61                 0                  1

In [ ]:
torch.manual_seed(2) 
max_iter=20
lambda0=0.05
w_threshold=0.1
d = xs_high.shape[1]
model=NotearsMLP(dims=[d, 10, 1], bias=True)
W_high_t = notears_nonlinear(model, xs_high, lambda1=lambda0, lambda2=lambda0, w_threshold=w_threshold,max_iter=max_iter)
W_high = W_high_t.T

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
node_label = []
node_edge_num_in = []
node_edge_num_out = []
for i in range(d):
    node_label.append(i+1)
    node_edge_num_in.append(np.sum(W_high[i,:]!=0))
    node_edge_num_out.append(np.sum(W_high[:,i]!=0))

data = {'node_label': node_label , 'node_edge_num_in': node_edge_num_in , 'node_edge_num_out': node_edge_num_out}
df = pd.DataFrame(data=data)
pd.set_option('display.max_rows', df.shape[0]+1)
df

node_label  node_edge_num_in  node_edge_num_out
0            1                 8                  0
1            2                 0                  1
2            3                 0                  0
3            4                 0                  1
4            5                 0                  0
5            6                 0                  0
6            7                 0                  1
7            8                 0                  0
8            9                 0                  2
9           10                 0                  1
10          11                 0                  0
11          12                 0                  0
12          13                 0                  0
13          14                 0                  0
14          15                 0                  0
15          16                 0                  0
16          17                 0                  2
17          18                 9                  0
18          19                 0                  0
19          20                 0                  0
20          21                 0                  1
21          22                 0                  1
22          23                 4                  0
23          24                 0                  0
24          25                 0                  2
25          26                 0                  1
26          27                 0                  2
27          28                 0                  0
28          29                 0                  2
29          30                 0                  0
30          31                 0                  1
31          32                 0                  1
32          33                 0                  0
33          34                 0                  0
34          35                 0                  0
35          36                 0                  1
36          37                 0                  0
37          38                 0                  0
38          39                 0                  1
39          40                 0                  0
40          41                 0                  0
41          42                 0                  1
42          43                 0                  0
43          44                 0                  0
44          45                 0                  1
45          46                 0                  0
46          47                 0                  0
47          48                 0                  0
48          49                 0                  0
49          50                 0                  0
50          51                 0                  0
51          52                 0                  0
52          53                 0                  0
53          54                 0                  0
54          55                 0                  0
55          56                 0                  0
56          57                 0                  0
57          58                 0                  1
58          59                 1                  0
59          60                 0                  1
60          61                 4                  1

In [ ]:
print(np.sum(W_low!=0))
print(np.sum(W_high!=0))

9
26


In [ ]:
print((np.array(range(d))+1)[W_low[17,:]!=0])
print((np.array(range(d))+1)[W_low[22,:]!=0])

[19 22 34 41]
[16 22 31 45]


In [ ]:
print((np.array(range(d))+1)[W_high[0,:]!=0])
print((np.array(range(d))+1)[W_high[17,:]!=0])

[ 7  9 17 25 27 29 39 60]
[ 4  9 17 25 26 27 29 32 42]


In [ ]:
for i in range(d):
    if np.sum(W_low[i,:])!=0:
        print("node",str(i+1),": ",(np.array(range(d))+1)[W_low[i,:]!=0])

node 18 :  [19 22 34 41]
node 23 :  [16 22 31 45]
node 59 :  [61]


In [ ]:
for i in range(d):
    if np.sum(W_high[i,:])!=0:
       print("node",str(i+1),": ",(np.array(range(d))+1)[W_high[i,:]!=0])

node 1 :  [ 7  9 17 25 27 29 39 60]
node 18 :  [ 4  9 17 25 26 27 29 32 42]
node 23 :  [21 22 31 45]
node 59 :  [61]
node 61 :  [ 2 10 36 58]


In [ ]:
torch.manual_seed(2) 
max_iter=20
lambda0=0.03
w_threshold=0.1
d = xs_low.shape[1]
model=NotearsMLP(dims=[d, 10, 1], bias=True)
W_low_t = notears_nonlinear(model, xs_low, lambda1=lambda0, lambda2=lambda0, w_threshold=w_threshold,max_iter=max_iter)
W_low = W_low_t.T

0
1
2
3
4
5
6
7
8
9


In [ ]:
torch.manual_seed(2) 
max_iter=20
lambda0=0.03
w_threshold=0.1
d = xs_high.shape[1]
model=NotearsMLP(dims=[d, 10, 1], bias=True)
W_high_t = notears_nonlinear(model, xs_high, lambda1=lambda0, lambda2=lambda0, w_threshold=w_threshold,max_iter=max_iter)
W_high = W_high_t.T

0
1
2
3
4
5
6
7
8


In [ ]:
import matplotlib.pyplot as plt
def imshow_zero_center(image, **kwargs):
  lim = np.max(abs(image))
  plt.imshow(image, vmin=-lim, vmax=lim, cmap='seismic', **kwargs)
  plt.colorbar()
imshow_zero_center(W_low)

In [ ]:
import matplotlib.pyplot as plt
def imshow_zero_center(image, **kwargs):
  lim = np.max(abs(image))
  plt.imshow(image, vmin=-lim, vmax=lim, cmap='seismic', **kwargs)
  plt.colorbar()
imshow_zero_center(W_high)